/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionrecetas;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InterfazGrafica extends javax.swing.JFrame {

    private String rutaArchivoRecetas = null;
    private String rutaArchivoIngredientes = null;
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonArchivoRecetas = new javax.swing.JButton();
        TextFieldArchivoRecetas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaArchivoRecetas = new javax.swing.JTextArea();
        buttonArchivoIngredientes = new javax.swing.JButton();
        TextFieldArchivoIngredientes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaArchivoIngredientes = new javax.swing.JTextArea();
        buttonProcesar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador Recetas");

        buttonArchivoRecetas.setText("Elegir archivo recetas");
        buttonArchivoRecetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonArchivoRecetasActionPerformed(evt);
            }
        });

        TextFieldArchivoRecetas.setEditable(false);

        TextAreaArchivoRecetas.setEditable(false);
        TextAreaArchivoRecetas.setColumns(20);
        TextAreaArchivoRecetas.setRows(5);
        jScrollPane1.setViewportView(TextAreaArchivoRecetas);

        buttonArchivoIngredientes.setText("Elegir archivo ingredientes");
        buttonArchivoIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonArchivoIngredientesActionPerformed(evt);
            }
        });

        TextFieldArchivoIngredientes.setEditable(false);

        TextAreaArchivoIngredientes.setEditable(false);
        TextAreaArchivoIngredientes.setColumns(20);
        TextAreaArchivoIngredientes.setRows(5);
        jScrollPane2.setViewportView(TextAreaArchivoIngredientes);

        buttonProcesar.setText("Procesar");
        buttonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProcesarActionPerformed(evt);
            }
        });

        textAreaResultado.setEditable(false);
        textAreaResultado.setColumns(20);
        textAreaResultado.setRows(5);
        jScrollPane3.setViewportView(textAreaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldArchivoRecetas)
                            .addComponent(buttonArchivoRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonArchivoIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextFieldArchivoIngredientes))
                        .addGap(170, 170, 170))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(buttonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonArchivoIngredientes)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldArchivoIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonArchivoRecetas)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldArchivoRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(buttonProcesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonArchivoRecetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonArchivoRecetasActionPerformed
        JFileChooser fileChooser = new JFileChooser (new File("./files"));
        
        int response = fileChooser.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION){
        rutaArchivoRecetas = fileChooser.getSelectedFile().getAbsolutePath();
        TextFieldArchivoRecetas.setText(rutaArchivoRecetas);
        
        File f = new File (rutaArchivoRecetas);
        try{
            Scanner sc = new Scanner (f);
            while (sc.hasNextLine()){
                TextAreaArchivoRecetas.append(sc.nextLine() + "\n");
            }
        }catch (FileNotFoundException ex){
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_buttonArchivoRecetasActionPerformed

    private void buttonArchivoIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonArchivoIngredientesActionPerformed
        JFileChooser fileChooser = new JFileChooser (new File("./files"));
        
        int response = fileChooser.showOpenDialog(this);
        
        if (response == JFileChooser.APPROVE_OPTION){
        rutaArchivoIngredientes = fileChooser.getSelectedFile().getAbsolutePath();
        TextFieldArchivoIngredientes.setText(rutaArchivoIngredientes);
        
        File f = new File (rutaArchivoIngredientes);
        try{
            Scanner sc = new Scanner (f);
            while (sc.hasNextLine()){
                TextAreaArchivoIngredientes.append(sc.nextLine() + "\n");
            }
        }catch (FileNotFoundException ex){
            Logger.getLogger(InterfazGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_buttonArchivoIngredientesActionPerformed

    private void buttonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProcesarActionPerformed
        if(rutaArchivoRecetas == null){
            JOptionPane.showMessageDialog(this, "falta abrir el archivo recetas", "Falta archivo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(rutaArchivoIngredientes == null){
            JOptionPane.showMessageDialog(this, "Falta abrir el archivo ingredientes", "Falta archivo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String resultado = "Puedo hacer la receta";
        textAreaResultado.append(resultado);
    }//GEN-LAST:event_buttonProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaArchivoIngredientes;
    private javax.swing.JTextArea TextAreaArchivoRecetas;
    private javax.swing.JTextField TextFieldArchivoIngredientes;
    private javax.swing.JTextField TextFieldArchivoRecetas;
    private javax.swing.JButton buttonArchivoIngredientes;
    private javax.swing.JButton buttonArchivoRecetas;
    private javax.swing.JButton buttonProcesar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textAreaResultado;
    // End of variables declaration//GEN-END:variables
}
